version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    hostname: app
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    image: mongo:4.0.7
    container_name: "mongodb"
    hostname: mongodb-host
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=db
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/01_mongo-init.js:ro

networks:
  my-network:
    driver: bridge