version: '3'
services:

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - app-mongo
    links:
      - app-mongo
  app-mongo:
    build: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: db
    volumes:
      - ./mongo/scripts/mongo-init.js:/docker-entrypoint-initdb.d/01_mongo-init.js:ro
    container_name: app-mongo