app:
  encryption.secret: aaaaaaaaaaaaaaaaaaaaaaaa
  direccion: 'http://localhost:${server.port}'
  jobs.reservas-job: '0 0 0 * * *'
server:
  port: 8080
spring:
  data:
    mongodb:
#      uri: mongodb://mongo:27017/db
      username: user
      password: pass
#      uri: mongodb://localhost:27017/db
      database: db
      host: app-mongo
#      host: mongodb
      port: 27017
  profiles:
    active: mail