spring:
  mail:
    properties:
      mail:
        smtp:
          connecttimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls.enable: true
          auth: true
    host:
    password:
    port:
    username: