app:
  encryption.secret: aaaaaaaaaaaaaaaaaaaaaaaa
  direccion: 'http://localhost:${server.port}'
  jobs.reservas-job: '0 0 0 * * *'
server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://api_user:NdEep0XLpMNKUmgQVa81oDCx7mrSRodh0Z79qdX3@mongodb-host:27017/db
  profiles:
    active: mail